apiVersion: v1
data:
  JICOFO_AUTH_PASSWORD: {{ if $.Values.JICOFO_AUTH_PASSWORD }}{{ $.Values.JICOFO_AUTH_PASSWORD | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  JICOFO_COMPONENT_SECRET: {{ if $.Values.JICOFO_COMPONENT_SECRET }}{{ $.Values.JICOFO_COMPONENT_SECRET | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  JVB_AUTH_PASSWORD: {{ if $.Values.JVB_AUTH_PASSWORD }}{{ $.Values.JVB_AUTH_PASSWORD | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  JVB_STUN_SERVERS: {{ $.Values.JVB_STUN_SERVERS | b64enc }}
  PUBLIC_URL: {{ if $.Values.PUBLIC_URL }}{{ $.Values.PUBLIC_URL | b64enc }}{{ else }}{{ if $.Values.haproxy.ingress.tlsEnable }}{{ print "https://" $.Values.haproxy.ingress.host | b64enc }}{{ else }}{{ print "http://" $.Values.haproxy.ingress.host | b64enc }}{{ end }}{{ end }}
  TZ: {{ $.Values.TZ | b64enc }}
kind: Secret
metadata:
  labels:
    scope: jitsi
  name: jitsi-config
  namespace: {{ $.Values.namespace }}
type: Opaque
