apiVersion: v1
kind: Service
metadata:
  labels:
    scope: jitsi
    service: {{ $.Values.web.name }}
  name: {{ $.Values.web.name }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    k8s-app: {{ $.Values.web.name }}
    scope: jitsi
